name: melmo
description: "A new Flutter project for melmo."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.1'

dependencies:
  flutter:
    sdk: flutter
  
  # Gestion de l'état et icônes
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  
  # Stockage local et utilitaires
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  
  # Firebase (Backend)
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.0
  google_sign_in: ^6.2.1
  
  # 💳 Passerelle de Paiement & Transactions
  flutterwave_standard: ^1.1.0
  uuid: ^4.3.3
  
  # Utilitaires divers
  image_picker: ^1.2.1
  http: ^1.6.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  share_plus: ^13.1.0
  cloud_functions: ^5.6.2
  firebase_app_check: ^0.3.2+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # ✅ Ajouté pour générer l'icône de l'application sur ton tel
  flutter_launcher_icons: ^0.14.4

# ✅ Configuration de l'icône de l'application (Logo MoMart)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2.png"
  adaptive_icon_background: "#ffffff" # Fond blanc derrière ton caddie orange
  adaptive_icon_foreground: "assets/images/logo2.png"

flutter:
  uses-material-design: true

  # ✅ Déclaration des assets
  assets:
    - assets/images/