// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeD-fgELMqOjW-tFk-PCdwS8vvTcNB964',
    appId: '1:1024396916109:web:63f079d5613126737ab9c4',
    messagingSenderId: '1024396916109',
    projectId: 'mohamed-app-xyz123',
    authDomain: 'mohamed-app-xyz123.firebaseapp.com',
    storageBucket: 'mohamed-app-xyz123.firebasestorage.app',
    measurementId: 'G-MSCVXPHRP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFSiyMiNWXpRJI5JAvvxKsn4YF6QO9lL8',
    appId: '1:1024396916109:android:2d0818c185e1616e7ab9c4',
    messagingSenderId: '1024396916109',
    projectId: 'mohamed-app-xyz123',
    storageBucket: 'mohamed-app-xyz123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYpgeyCqV0tHHHJF2h5qMGC51BGGzTLgY',
    appId: '1:1024396916109:ios:65b42e7507d52b4b7ab9c4',
    messagingSenderId: '1024396916109',
    projectId: 'mohamed-app-xyz123',
    storageBucket: 'mohamed-app-xyz123.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYpgeyCqV0tHHHJF2h5qMGC51BGGzTLgY',
    appId: '1:1024396916109:ios:65b42e7507d52b4b7ab9c4',
    messagingSenderId: '1024396916109',
    projectId: 'mohamed-app-xyz123',
    storageBucket: 'mohamed-app-xyz123.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeD-fgELMqOjW-tFk-PCdwS8vvTcNB964',
    appId: '1:1024396916109:web:463de5fd50fcd9e87ab9c4',
    messagingSenderId: '1024396916109',
    projectId: 'mohamed-app-xyz123',
    authDomain: 'mohamed-app-xyz123.firebaseapp.com',
    storageBucket: 'mohamed-app-xyz123.firebasestorage.app',
    measurementId: 'G-RWD31M3DDT',
  );
}
